@url=https://www.liuxiu.xyz/api
@url2=http://localhost:3000/api
@ctjson=Content-Type: application/json

###
get {{url}}

###
post {{url}}/register
{{ctjson}}

{
    "username":"123ad",
    "psd":"123a"
}


###
post {{url}}/user_history
{{ctjson}}

{
    "userid":"history_1",
    "tripid":"31281323"
}

###
post {{url}}/login
{{ctjson}}

{
    "username":"da",
    "psd":"12"
}

###
get {{url}}/historylist/1/0/10

###
get {{url}}/tripslist/1/0/10

###
get {{url}}/search/游/0/10

###
get {{url}}/searchbydate/1/游/0/5

###
get {{url}}/searchbylike/1/北京/0/5

###
get {{url}}/searchbyview/1/北京/0/5


###
post {{url}}/addlike
{{ctjson}}

{
    "userid":"1",
    "tripid":"31277605"
}

###
post {{url}}/dellike
{{ctjson}}

{
    "userid":"1",
    "tripid":"31277605"
}

###
post {{url}}/likelist/0/5
{{ctjson}}

{
    "id":"1"
}

###
post {{url}}/addtrips
{{ctjson}}

{
    "name":"adqergf",
    "authorId":"123421",
    "publishTime":"1997-07-1",
    "picUrl":"picUrl6576571234",
    "authorName":"authorNameadqergf",
    "authorHeadImg":"authorHeadImg6576571234",
    "picNum":1,
    "sourse":"原创",
    "summary":"这是游记简介"
}

###
get {{url}}/tripimages/31281326/0

###
post {{url}}/addusertag
{{ctjson}}

{
    "userid":"1",
    "tripid":"31277605"
}

###
post {{url}}/delusertag
{{ctjson}}

{
    "userid":"1",
    "tripid":"31277605"
}


###
post {{url}}/getusertag
{{ctjson}}

{
    "userid":"1"
}

###
post {{url}}/getrecommendlist
{{ctjson}}

{
    "userid":"1",
    "start":"0",
    "end":"9"
}

###
post {{url}}/addtest
{{ctjson}}

{
    "userid":"1",
    "arr":[1,12312,2,1123,3,1434]
}

###
get {{url}}/selftrips/1/0/4

###
get {{url}}/get_search_history/1

###
get {{url}}/tripdetail/1/31281323

###
get {{url}}/imageurls/31281327

###
get {{url}}/getimage/31281327/tripImage_0.jpg